### ISSUE TITLE
Right click

### ISSUE THREAD

**Issue by jklnz** [davidmckenzie/pagermon#47]
Hey @davidmckenzie 
Would it be possible to enable the right click options to open links in new tabs on source capcode agency and alias on the index pages please? Atleast in Chrome these can only be opened by left clicking.

![image](https://user-images.githubusercontent.com/26646690/27515057-e0765f4a-59ee-11e7-8aa8-0f69f7164bbb.png)

**Comment by davidmckenzie** [comment]
Looking at this again - clicking on source/capcode/agency/alias should show a popover with contextual links (filter, edit, etc.), and maybe some more information.

E.g. if logged in and clicking on the alias, it could show the settings of that alias or something. If not logged in, perhaps it could show a description or comment field for the alias, as well as filter links.

Consider making the edit link open a modal instead of redirecting to the edit page.
